### ISSUE TITLE
Duplicate address code error

### ISSUE THREAD

**Issue by rossiter10** [nopSolutions/avalara-plugin-for-nopcommerce#10]
I'm getting some of these errors on a production site:
```
Avalara tax request error: { "ResultCode": "Error", "Messages": [ { "Summary": "Duplicate Address Code 0.", "Details": "There are duplicate address codes used in the request. Address code should be unique for addresses.", "RefersTo": "Addresses[2]", "Severity": "Error", "Source": "Avalara.AvaTax.Services.Tax"} ] }

System.Net.WebException: The remote server returned an error: (500) Internal Server Error. at System.Net.HttpWebRequest.GetResponse() at Nop.Plugin.Tax.Avalara.Helpers.AvalaraTaxHelper.PostTaxRequest(TaxRequest taxRequest, AvalaraTaxSettings avalaraTaxSettings, ILogger logger)
```

I haven't been able to reproduce at all. I even run locally and manually change the `Addresses `part of `TaxRequest` to be the same addresses, but I don't still don't get the error. From what I see, all of these errors come from Guest customers, and also during checkout (/checkout/opcconfirmorder/).

Any thoughts?

**Comment by RomanovM** [comment]
Cannot reproduce this error in the latest version
