### ISSUE TITLE
Update to 4.20??

### ISSUE THREAD

**Issue by SteveEmbry** [nopSolutions/avalara-plugin-for-nopcommerce#16]
Hello-

This is proving to be a crucial plugin for our business and we're ready to upgrade our site to nopCommerce 4.20, so we are very hopeful that the updated plugin will be released very soon.

Is that a possibility?

Thanks,
embryo

**Comment by skoshelev** [comment]
Hi @SteveEmbry. This plugin is available out of the box in nopCommerce starting version 4.20

**Comment by SteveEmbry** [comment]
Awesome, thanks!
