### ISSUE TITLE
AvaTax codes for Avalara Tax Plugin

### ISSUE THREAD

**Issue by angbisoft** [nopSolutions/avalara-plugin-for-nopcommerce#17]
Hi,

I could not find any documentation about how to associate a product with an AvaTax code. I tried the nopCommerce forums (https://www.nopcommerce.com/en/boards/topic/85193/avatax-code-for-avalara-tax-plugin) nobody replied for a month. 

My current thinking is that, I need to pick tax category names such as PF050211 (i.e. AvaTax Codes) and assign tax categories to products. But it is just my guess, I could not find any documentation which clearly explains the concept.

I realize, this might not be considered as bug/feature etc, and I apologize for that. However, I suggest such issues should be documented in the README or the Wiki section.

Thanks a lot.

**Comment by RomanovM** [comment]
@angbisoft  Correct, AvaTax codes are tax categories in nopCommerce. First, you need to create or import them on the tax categories page in admin area, then assign them to products.

**Comment by RomanovM** [comment]
Moved to https://github.com/nopSolutions/nopCommerce-Docs/issues/191
