### ISSUE TITLE
4.00 support

### ISSUE THREAD

**Issue by travisterrell** [nopSolutions/avalara-plugin-for-nopcommerce#7]
I've seen a few commits in the branch for version 4.00, but they are more than 2 weeks old. How quickly is support expected to become available? 

Also, if the update isn't expected to be available soon, could you provide some details on what remains to be completed? I'd be glad to develop on that branch, as I need to add this functionality to a client's site very soon.

**Comment by skoshelev** [comment]
Hello @travisterrell . We're planning to finish this plugin in near future, we must add some new functionals and test them.

**Comment by RomanovM** [comment]
Done https://github.com/nopSolutions/avalara-plugin-for-nopcommerce/commit/92ae669a7db96677d821369e98b576b185cc3603
